### ISSUE TITLE
order is important in content json file

### ISSUE THREAD

**Issue by lamujeresponja** [jeremyfa/node-redis-dump#2]
Hi Jeremy!

I have Redis 2.4.

When I try to import a json file with various typesdata how for example strings and list, my redis bad-done if the type list is in the begin of the file. If i exchange the order, first the strings and after the list, then well-done my import.

Do you know this?

My json file is this:

{
    "Config:Types": {
        "type": "list",
        "value": [
            "4",
            "16",
            "14"
        ]
    },
    "Config:3:V3:Type": {
        "type": "string",
        "value": "float"
    }
}

Thank you very much
Elvira.

**Comment by lamujeresponja** [comment]
Can you see that?

Thanks!

**Comment by jeremyfa** [comment]
I'm not sure about the issue, but it was never a goal to respect the order of keys in the json format, nor can be garanteed. I am also not sure about what the issues are with not respecting order as each key in the redis db should not depend to the other ones (or at least their order)? Closing this for now.
