### ISSUE TITLE
process does not return with a filter without match, unless json

### ISSUE THREAD

**Issue by TiTi** [jeremyfa/node-redis-dump#9]
Exemple: (with no key **account:930050685**)

```
CALL node_modules\.bin\redis-dump.cmd -h 192.168.0.3 -f "account:930050685"  > account.json
```

Same with wildcard

When `--json` is used, the process returns and account.json contains as expected an empty object: `{}`.

**Comment by jeremyfa** [comment]
Yes, I think you are running into a known issue: process doesn't return when the database is empty (no key). Will have to make a fix for that. However it should be fine as soon as the db contains something right? (still the issue needs to be fixed)

Thanks for reporting!

**Comment by TiTi** [comment]
Yes.

To get a better understanding, it's important to know that I'm looking for a specific key or a key with a wildcard, but I don't know if it exists in Redis yet.
For instance, let's say I'm storing a bunch of keys like :

```
  user:<id>
```

Which holds user information like custom preferences when the user changed the default value.
So, key is present when the user changed a setting, otherwise it's not.

Imagine I'd like to export the specific user:123456 just to grab all his redis data.
Well, I might be stuck if the key doesn't exist....

The workaround I used was to export as json which gives me an empty object as expected.
